apiVersion: v1
kind: ConfigMap
metadata:
  name: wellness-ai-config
  namespace: wellness-ai
data:
  # Application settings
  APP_NAME: "Enterprise Employee Wellness AI"
  APP_VERSION: "1.0.0"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  
  # API settings
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  
  # Database settings
  DATABASE_URL: "postgresql://wellness_user:wellness_pass@wellness-postgres:5432/wellness_db"
  REDIS_URL: "redis://wellness-redis:6379"
  VECTOR_DB_URL: "chromadb://wellness-chromadb:8000"
  
  # AI settings
  DEFAULT_MODEL: "gpt-4"
  EMBEDDING_MODEL: "text-embedding-ada-002"
  
  # Agent settings
  WELLNESS_COMPANION_MODEL: "gpt-4"
  WELLNESS_MEMORY_TYPE: "episodic"
  WELLNESS_RISK_THRESHOLD: "0.7"
  RESOURCE_VECTOR_DB: "chromadb"
  RESOURCE_EMBEDDING_MODEL: "text-embedding-ada-002"
  SENTIMENT_MODELS: "vader,roberta"
  RISK_INDICATORS: "burnout,stress_spike,toxic_patterns"
  ANALYTICS_AGGREGATION_WINDOW: "7d"
  ANALYTICS_RETENTION_DAYS: "365"
  
  # Security settings
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  DP_EPSILON: "1.0"
  ANONYMIZATION_ENABLED: "true"
  
  # Monitoring settings
  PROMETHEUS_ENDPOINT: "http://wellness-prometheus:9090"
  GRAFANA_URL: "http://wellness-grafana:3000"
  OPA_POLICY_URL: "http://wellness-opa:8181"
  
  # CORS settings
  CORS_ORIGINS: "http://localhost:3000,http://localhost:3001,https://wellness-ai.example.com"
